services:
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-aperture.rule=Host(`aperture.local.js42.io`)"
    networks:
      - default
      - frontend

networks:
  frontend:
    external: true
